# Generated by Django 5.2.4 on 2025-07-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewerID', models.CharField(max_length=100)),
                ('asin', models.CharField(max_length=100)),
                ('reviewrName', models.CharField(max_length=50)),
                ('reviewTime', models.DateField()),
                ('reviewText', models.CharField(max_length=500)),
            ],
        ),
    ]
